<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="5" failed="3" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-04T20:35:23 IST" name="Master Suite" finished-at="2022-07-04T20:35:23 IST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- Master Suite -->
  <suite started-at="2022-07-04T20:35:23 IST" name="Reggression Suite" finished-at="2022-07-04T20:35:23 IST" duration-ms="28">
    <groups>
    </groups>
    <test started-at="2022-07-04T20:35:23 IST" name="Reggression Login Test" finished-at="2022-07-04T20:35:23 IST" duration-ms="15">
      <class name="Reggression.TestCase1">
        <test-method is-config="true" signature="openDBConn()[pri:0, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="openDBConn" finished-at="2022-07-04T20:35:23 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openDBConn -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="launchBrowser" finished-at="2022-07-04T20:35:23 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="doUserReg()[pri:1, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="doUserReg" finished-at="2022-07-04T20:35:23 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="closebrowser" finished-at="2022-07-04T20:35:23 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="launchBrowser" finished-at="2022-07-04T20:35:23 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="doLogin()[pri:2, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="doLogin" finished-at="2022-07-04T20:35:23 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="closebrowser" finished-at="2022-07-04T20:35:23 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="closeDBConn()[pri:0, instance:Reggression.TestCase1@4d5d943d]" started-at="2022-07-04T20:35:23 IST" name="closeDBConn" finished-at="2022-07-04T20:35:23 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- Reggression.TestCase1 -->
    </test> <!-- Reggression Login Test -->
    <test started-at="2022-07-04T20:35:23 IST" name="Reggression Validate tittle Test" finished-at="2022-07-04T20:35:23 IST" duration-ms="7">
      <class name="Reggression.TestCase2">
        <test-method signature="validateTitles()[pri:0, instance:Reggression.TestCase2@a1153bc]" started-at="2022-07-04T20:35:23 IST" name="validateTitles" finished-at="2022-07-04T20:35:23 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Gmail.com] but found [Yahoo.com],
Image validation failed expected [true] but found [false],
TextBox Validation failed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Gmail.com] but found [Yahoo.com],
Image validation failed expected [true] but found [false],
TextBox Validation failed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Reggression.TestCase2.validateTitles(TestCase2.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- Reggression.TestCase2 -->
    </test> <!-- Reggression Validate tittle Test -->
  </suite> <!-- Reggression Suite -->
  <suite started-at="2022-07-04T20:35:22 IST" name="Functional Suite" finished-at="2022-07-04T20:35:23 IST" duration-ms="245">
    <groups>
    </groups>
    <test started-at="2022-07-04T20:35:22 IST" name="Login Test" finished-at="2022-07-04T20:35:22 IST" duration-ms="80">
      <class name="TestCases.TestCase1">
        <test-method is-config="true" signature="openDBConn()[pri:0, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="openDBConn" finished-at="2022-07-04T20:35:22 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openDBConn -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="launchBrowser" finished-at="2022-07-04T20:35:22 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="doUserReg()[pri:1, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="doUserReg" finished-at="2022-07-04T20:35:22 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="closebrowser" finished-at="2022-07-04T20:35:22 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="launchBrowser" finished-at="2022-07-04T20:35:22 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="doLogin()[pri:2, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="doLogin" finished-at="2022-07-04T20:35:22 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="closebrowser" finished-at="2022-07-04T20:35:22 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="closeDBConn()[pri:0, instance:TestCases.TestCase1@9f116cc]" started-at="2022-07-04T20:35:22 IST" name="closeDBConn" finished-at="2022-07-04T20:35:22 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- TestCases.TestCase1 -->
    </test> <!-- Login Test -->
    <test started-at="2022-07-04T20:35:23 IST" name="validate Title Test" finished-at="2022-07-04T20:35:23 IST" duration-ms="17">
      <class name="TestCases.TestCase2">
        <test-method signature="validateTitles()[pri:0, instance:TestCases.TestCase2@38d8f54a]" started-at="2022-07-04T20:35:23 IST" name="validateTitles" finished-at="2022-07-04T20:35:23 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Gmail.com] but found [Yahoo.com],
Image validation failed expected [true] but found [false],
TextBox Validation failed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Gmail.com] but found [Yahoo.com],
Image validation failed expected [true] but found [false],
TextBox Validation failed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.TestCase2.validateTitles(TestCase2.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- TestCases.TestCase2 -->
    </test> <!-- validate Title Test -->
    <test started-at="2022-07-04T20:35:23 IST" name="Dependency Test" finished-at="2022-07-04T20:35:23 IST" duration-ms="29">
      <class name="TestCases.TestCase3">
        <test-method signature="doUserReg()[pri:1, instance:TestCases.TestCase3@145f66e3]" started-at="2022-07-04T20:35:23 IST" name="doUserReg" finished-at="2022-07-04T20:35:23 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User failed to register]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User failed to register
at org.testng.Assert.fail(Assert.java:99)
at TestCases.TestCase3.doUserReg(TestCase3.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method signature="doLogin()[pri:2, instance:TestCases.TestCase3@145f66e3]" started-at="2022-07-04T20:35:23 IST" name="doLogin" finished-at="2022-07-04T20:35:23 IST" depends-on-methods="TestCases.TestCase3.doUserReg" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:TestCases.TestCase3@145f66e3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:TestCases.TestCase3@145f66e3] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method signature="thirdTest()[pri:3, instance:TestCases.TestCase3@145f66e3]" started-at="2022-07-04T20:35:23 IST" name="thirdTest" finished-at="2022-07-04T20:35:23 IST" depends-on-methods="TestCases.TestCase3.doUserReg" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method signature="fourthTest()[pri:4, instance:TestCases.TestCase3@145f66e3]" started-at="2022-07-04T20:35:23 IST" name="fourthTest" finished-at="2022-07-04T20:35:23 IST" depends-on-methods="TestCases.TestCase3.doUserReg" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.fourthTest()[pri:4, instance:TestCases.TestCase3@145f66e3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.fourthTest()[pri:4, instance:TestCases.TestCase3@145f66e3] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthTest -->
      </class> <!-- TestCases.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
